files:
- generatedChecksum: 88EC0E8DE9765171A5719AD6829DF317
  logicalPath: config/pic32mk_mcj_curiosity_pro/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 88EC0E8DE9765171A5719AD6829DF317
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: 0D8259000E4B01ECC04621817B211E54
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0D8259000E4B01ECC04621817B211E54
- generatedChecksum: C1E9F59B0D7540E41773AF56AAFAE1AC
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: C1E9F59B0D7540E41773AF56AAFAE1AC
- generatedChecksum: null
  logicalPath: ''
  name: main_pic32mz_ef_sk.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 6AC1ECF1B1D9F9696C905F0C2082C3B7
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/canfd
  name: plib_canfd1.c
  physicalPath: peripheral/canfd
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6AC1ECF1B1D9F9696C905F0C2082C3B7
- generatedChecksum: 504299FF23D8C2AD97FA793077C82717
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 504299FF23D8C2AD97FA793077C82717
- generatedChecksum: 1C64A0CC3068C1F1EB55F6817B1579A6
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/coretimer
  name: plib_coretimer.c
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1C64A0CC3068C1F1EB55F6817B1579A6
- generatedChecksum: 91641B47CA8C74D682EF7877C9099E81
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/dmac
  name: plib_dmac.c
  physicalPath: peripheral/dmac
  security: NON_SECURE
  type: SOURCE
  userChecksum: 91641B47CA8C74D682EF7877C9099E81
- generatedChecksum: 27D95DD428DFEB82E8E68E3D7682A3BE
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 27D95DD428DFEB82E8E68E3D7682A3BE
- generatedChecksum: C9B1A4DD0F6B417C21CC1C11B9B999D6
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: C9B1A4DD0F6B417C21CC1C11B9B999D6
- generatedChecksum: 9CADBF4ECB6F0E67433914D3D5143E5C
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/spi/spi_master
  name: plib_spi1_master.c
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9CADBF4ECB6F0E67433914D3D5143E5C
- generatedChecksum: 61382DAE2B82E5F4D68EDE7917667C81
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/spi/spi_master
  name: plib_spi2_master.c
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: SOURCE
  userChecksum: 61382DAE2B82E5F4D68EDE7917667C81
- generatedChecksum: 833C5EECB1A2761B58D96453FA10BE2E
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/uart
  name: plib_uart1.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3E7361FDEE956C7D2737559C5316031E
- generatedChecksum: 188D068D833C10969DD9499A65EB721F
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/uart
  name: plib_uart2.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 188D068D833C10969DD9499A65EB721F
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config/pic32mk_mcj_curiosity_pro/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: 4A0E3363502FD80F44339C0531A9F82D
  logicalPath: config/pic32mk_mcj_curiosity_pro/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: 4A0E3363502FD80F44339C0531A9F82D
- generatedChecksum: 0A42B2797B6B39DA0B343FD9536FD5AC
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 0A42B2797B6B39DA0B343FD9536FD5AC
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: AAA04F4A3D0A6CC5F84D6B07B027B8C7
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/canfd
  name: plib_canfd1.h
  physicalPath: peripheral/canfd
  security: NON_SECURE
  type: HEADER
  userChecksum: AAA04F4A3D0A6CC5F84D6B07B027B8C7
- generatedChecksum: AEFE39C8E52415FE642815364C699E0C
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/canfd
  name: plib_canfd_common.h
  physicalPath: peripheral/canfd
  security: NON_SECURE
  type: HEADER
  userChecksum: AEFE39C8E52415FE642815364C699E0C
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 3D6EB2BF99796DE22C8637CC7F213F11
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/coretimer
  name: plib_coretimer.h
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: 3D6EB2BF99796DE22C8637CC7F213F11
- generatedChecksum: D4A1E2329C517DB8AB49B9143079554F
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/dmac
  name: plib_dmac.h
  physicalPath: peripheral/dmac
  security: NON_SECURE
  type: HEADER
  userChecksum: D4A1E2329C517DB8AB49B9143079554F
- generatedChecksum: 23F86588C83891551C404C1BA77F9655
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 23F86588C83891551C404C1BA77F9655
- generatedChecksum: 86DD4AE3C8D3D49AD025516F3BE774C2
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 86DD4AE3C8D3D49AD025516F3BE774C2
- generatedChecksum: 2BFA27375C2515B7583152035E1731E4
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/spi/spi_master
  name: plib_spi1_master.h
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: 2BFA27375C2515B7583152035E1731E4
- generatedChecksum: ED75DA47F560AA4C85ABB33675D1033F
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/spi/spi_master
  name: plib_spi2_master.h
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: ED75DA47F560AA4C85ABB33675D1033F
- generatedChecksum: CFA758C8B7258190473EF7C60C4BA4E9
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/spi/spi_master
  name: plib_spi_master_common.h
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: CFA758C8B7258190473EF7C60C4BA4E9
- generatedChecksum: 7B9E1ABB4EB466D0BB9D0E143BDD2E90
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/uart
  name: plib_uart1.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 7B9E1ABB4EB466D0BB9D0E143BDD2E90
- generatedChecksum: 802E41280DEA41F6B6FF1E79BC50C503
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/uart
  name: plib_uart2.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 802E41280DEA41F6B6FF1E79BC50C503
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: F763B024E08CC03A462BEA30DDC5C5D7
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: p32MK0512MCJ064.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: F763B024E08CC03A462BEA30DDC5C5D7
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcj_curiosity_pro;../src/packs/PIC32MK0512MCJ064_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcj_curiosity_pro;../src/packs/PIC32MK0512MCJ064_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
